import type { Metadata } from "next";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Tam Media",
  description: "Generated by abolfazl_j10",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR">
      <body dir="rtl">
        {children}
      </body>
    </html>
  );
}
